//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SADT.Modules.TechnicalTask.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SADT.Modules.TechnicalTask.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Accommodation category.
        /// </summary>
        public static string CategoryAccommodation {
            get {
                return ResourceManager.GetString("CategoryAccommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.
        /// </summary>
        public static string CategoryAccommodation1 {
            get {
                return ResourceManager.GetString("CategoryAccommodation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.1.
        /// </summary>
        public static string CategoryAccommodation11 {
            get {
                return ResourceManager.GetString("CategoryAccommodation11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.
        /// </summary>
        public static string CategoryAccommodation2 {
            get {
                return ResourceManager.GetString("CategoryAccommodation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.1.
        /// </summary>
        public static string CategoryAccommodation21 {
            get {
                return ResourceManager.GetString("CategoryAccommodation21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3.
        /// </summary>
        public static string CategoryAccommodation3 {
            get {
                return ResourceManager.GetString("CategoryAccommodation3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3.1.
        /// </summary>
        public static string CategoryAccommodation31 {
            get {
                return ResourceManager.GetString("CategoryAccommodation31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4.
        /// </summary>
        public static string CategoryAccommodation4 {
            get {
                return ResourceManager.GetString("CategoryAccommodation4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4.1.
        /// </summary>
        public static string CategoryAccommodation41 {
            get {
                return ResourceManager.GetString("CategoryAccommodation41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4.2.
        /// </summary>
        public static string CategoryAccommodation42 {
            get {
                return ResourceManager.GetString("CategoryAccommodation42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 5.
        /// </summary>
        public static string CategoryAccommodation5 {
            get {
                return ResourceManager.GetString("CategoryAccommodation5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 5.1.
        /// </summary>
        public static string CategoryAccommodation51 {
            get {
                return ResourceManager.GetString("CategoryAccommodation51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Climatic performance.
        /// </summary>
        public static string ClimaticPerformance {
            get {
                return ResourceManager.GetString("ClimaticPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на HL.
        /// </summary>
        public static string ClimaticPerformanceHL {
            get {
                return ResourceManager.GetString("ClimaticPerformanceHL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на T.
        /// </summary>
        public static string ClimaticPerformanceT {
            get {
                return ResourceManager.GetString("ClimaticPerformanceT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Y.
        /// </summary>
        public static string ClimaticPerformanceY {
            get {
                return ResourceManager.GetString("ClimaticPerformanceY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на YHL.
        /// </summary>
        public static string ClimaticPerformanceYHL {
            get {
                return ResourceManager.GetString("ClimaticPerformanceYHL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection type high voltage.
        /// </summary>
        public static string ConnectionTypeHighVoltage {
            get {
                return ResourceManager.GetString("ConnectionTypeHighVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на D.
        /// </summary>
        public static string ConnectionTypeHighVoltageD {
            get {
                return ResourceManager.GetString("ConnectionTypeHighVoltageD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Y.
        /// </summary>
        public static string ConnectionTypeHighVoltageY {
            get {
                return ResourceManager.GetString("ConnectionTypeHighVoltageY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yn.
        /// </summary>
        public static string ConnectionTypeHighVoltageYn {
            get {
                return ResourceManager.GetString("ConnectionTypeHighVoltageYn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection type low voltage.
        /// </summary>
        public static string ConnectionTypeLowVoltage {
            get {
                return ResourceManager.GetString("ConnectionTypeLowVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на D.
        /// </summary>
        public static string ConnectionTypeLowVoltageD {
            get {
                return ResourceManager.GetString("ConnectionTypeLowVoltageD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Y.
        /// </summary>
        public static string ConnectionTypeLowVoltageY {
            get {
                return ResourceManager.GetString("ConnectionTypeLowVoltageY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yn.
        /// </summary>
        public static string ConnectionTypeLowVoltageYn {
            get {
                return ResourceManager.GetString("ConnectionTypeLowVoltageYn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Z.
        /// </summary>
        public static string ConnectionTypeLowVoltageZ {
            get {
                return ResourceManager.GetString("ConnectionTypeLowVoltageZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Transformer cooling method.
        /// </summary>
        public static string CoolingMethod {
            get {
                return ResourceManager.GetString("CoolingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на C.
        /// </summary>
        public static string CoolingMethodC {
            get {
                return ResourceManager.GetString("CoolingMethodC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на D.
        /// </summary>
        public static string CoolingMethodD {
            get {
                return ResourceManager.GetString("CoolingMethodD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DC.
        /// </summary>
        public static string CoolingMethodDC {
            get {
                return ResourceManager.GetString("CoolingMethodDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на M.
        /// </summary>
        public static string CoolingMethodM {
            get {
                return ResourceManager.GetString("CoolingMethodM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MC.
        /// </summary>
        public static string CoolingMethodMC {
            get {
                return ResourceManager.GetString("CoolingMethodMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NC.
        /// </summary>
        public static string CoolingMethodNC {
            get {
                return ResourceManager.GetString("CoolingMethodNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NDC.
        /// </summary>
        public static string CoolingMethodNDC {
            get {
                return ResourceManager.GetString("CoolingMethodNDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NMC.
        /// </summary>
        public static string CoolingMethodNMC {
            get {
                return ResourceManager.GetString("CoolingMethodNMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Earthquake intensity, MSK-64 points.
        /// </summary>
        public static string EarthquakeIntensity {
            get {
                return ResourceManager.GetString("EarthquakeIntensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.
        /// </summary>
        public static string EarthquakeIntensity1 {
            get {
                return ResourceManager.GetString("EarthquakeIntensity1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.
        /// </summary>
        public static string EarthquakeIntensity2 {
            get {
                return ResourceManager.GetString("EarthquakeIntensity2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3.
        /// </summary>
        public static string EarthquakeIntensity3 {
            get {
                return ResourceManager.GetString("EarthquakeIntensity3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4.
        /// </summary>
        public static string EarthquakeIntensity4 {
            get {
                return ResourceManager.GetString("EarthquakeIntensity4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 5.
        /// </summary>
        public static string EarthquakeIntensity5 {
            get {
                return ResourceManager.GetString("EarthquakeIntensity5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 6.
        /// </summary>
        public static string EarthquakeIntensity6 {
            get {
                return ResourceManager.GetString("EarthquakeIntensity6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 7.
        /// </summary>
        public static string EarthquakeIntensity7 {
            get {
                return ResourceManager.GetString("EarthquakeIntensity7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 8.
        /// </summary>
        public static string EarthquakeIntensity8 {
            get {
                return ResourceManager.GetString("EarthquakeIntensity8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 9.
        /// </summary>
        public static string EarthquakeIntensity9 {
            get {
                return ResourceManager.GetString("EarthquakeIntensity9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на External insulation performance category.
        /// </summary>
        public static string ExternalInsulation {
            get {
                return ResourceManager.GetString("ExternalInsulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Frequency, Hz.
        /// </summary>
        public static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 50.
        /// </summary>
        public static string Frequency50 {
            get {
                return ResourceManager.GetString("Frequency50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 60.
        /// </summary>
        public static string Frequency60 {
            get {
                return ResourceManager.GetString("Frequency60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection type.
        /// </summary>
        public static string GroupType {
            get {
                return ResourceManager.GetString("GroupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0.
        /// </summary>
        public static string GroupType0 {
            get {
                return ResourceManager.GetString("GroupType0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.
        /// </summary>
        public static string GroupType1 {
            get {
                return ResourceManager.GetString("GroupType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 10.
        /// </summary>
        public static string GroupType10 {
            get {
                return ResourceManager.GetString("GroupType10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 11.
        /// </summary>
        public static string GroupType11 {
            get {
                return ResourceManager.GetString("GroupType11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.
        /// </summary>
        public static string GroupType2 {
            get {
                return ResourceManager.GetString("GroupType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3.
        /// </summary>
        public static string GroupType3 {
            get {
                return ResourceManager.GetString("GroupType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4.
        /// </summary>
        public static string GroupType4 {
            get {
                return ResourceManager.GetString("GroupType4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 5.
        /// </summary>
        public static string GroupType5 {
            get {
                return ResourceManager.GetString("GroupType5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 6.
        /// </summary>
        public static string GroupType6 {
            get {
                return ResourceManager.GetString("GroupType6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 7.
        /// </summary>
        public static string GroupType7 {
            get {
                return ResourceManager.GetString("GroupType7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 8.
        /// </summary>
        public static string GroupType8 {
            get {
                return ResourceManager.GetString("GroupType8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 9.
        /// </summary>
        public static string GroupType9 {
            get {
                return ResourceManager.GetString("GroupType9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Installation height above sea level, no more, m.
        /// </summary>
        public static string InstallationAltitude {
            get {
                return ResourceManager.GetString("InstallationAltitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Insulation processing mode.
        /// </summary>
        public static string InsulationMode {
            get {
                return ResourceManager.GetString("InsulationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A.
        /// </summary>
        public static string InsulationModeA {
            get {
                return ResourceManager.GetString("InsulationModeA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Internal insulation performance level.
        /// </summary>
        public static string InternalInsulation {
            get {
                return ResourceManager.GetString("InternalInsulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на a.
        /// </summary>
        public static string InternalInsulationa {
            get {
                return ResourceManager.GetString("InternalInsulationa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на b.
        /// </summary>
        public static string InternalInsulationb {
            get {
                return ResourceManager.GetString("InternalInsulationb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на I.
        /// </summary>
        public static string InternalInsulationI {
            get {
                return ResourceManager.GetString("InternalInsulationI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на II.
        /// </summary>
        public static string InternalInsulationII {
            get {
                return ResourceManager.GetString("InternalInsulationII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на III.
        /// </summary>
        public static string InternalInsulationIII {
            get {
                return ResourceManager.GetString("InternalInsulationIII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на II*.
        /// </summary>
        public static string InternalInsulationIIx {
            get {
                return ResourceManager.GetString("InternalInsulationIIx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IV.
        /// </summary>
        public static string InternalInsulationIV {
            get {
                return ResourceManager.GetString("InternalInsulationIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum deviation of short circuit losses of the main branch, %.
        /// </summary>
        public static string LoadLossesDeviationMaximum {
            get {
                return ResourceManager.GetString("LoadLossesDeviationMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimum deviation of short circuit losses of the main branch, %.
        /// </summary>
        public static string LoadLossesDeviationMinimum {
            get {
                return ResourceManager.GetString("LoadLossesDeviationMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load losses losses, W.
        /// </summary>
        public static string LoadLossesNominal {
            get {
                return ResourceManager.GetString("LoadLossesNominal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load mode.
        /// </summary>
        public static string LoadMode {
            get {
                return ResourceManager.GetString("LoadMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Long.
        /// </summary>
        public static string LoadModeLong {
            get {
                return ResourceManager.GetString("LoadModeLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Short.
        /// </summary>
        public static string LoadModeShort {
            get {
                return ResourceManager.GetString("LoadModeShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lower operating value of air temperature, С.
        /// </summary>
        public static string LowerOperatingTemperature {
            get {
                return ResourceManager.GetString("LowerOperatingTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum deviation of no-load current, %.
        /// </summary>
        public static string NoLoadCurrentDeviationMaximum {
            get {
                return ResourceManager.GetString("NoLoadCurrentDeviationMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimum deviation of no-load current,%.
        /// </summary>
        public static string NoLoadCurrentDeviationMinimum {
            get {
                return ResourceManager.GetString("NoLoadCurrentDeviationMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No-load current,%.
        /// </summary>
        public static string NoLoadCurrentNominal {
            get {
                return ResourceManager.GetString("NoLoadCurrentNominal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum deviation of no-load losses, %.
        /// </summary>
        public static string NoLoadLossesDeviationMaximum {
            get {
                return ResourceManager.GetString("NoLoadLossesDeviationMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimum deviation of no-load losses, %.
        /// </summary>
        public static string NoLoadLossesDeviationMinimum {
            get {
                return ResourceManager.GetString("NoLoadLossesDeviationMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No-load losses, W.
        /// </summary>
        public static string NoLoadLossesNominal {
            get {
                return ResourceManager.GetString("NoLoadLossesNominal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Excess of temperature of the upper layers of oil, С.
        /// </summary>
        public static string OilUpperLayersExcessTemperature {
            get {
                return ResourceManager.GetString("OilUpperLayersExcessTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of phases.
        /// </summary>
        public static string PhaseNumber {
            get {
                return ResourceManager.GetString("PhaseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.
        /// </summary>
        public static string PhaseNumber1 {
            get {
                return ResourceManager.GetString("PhaseNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3.
        /// </summary>
        public static string PhaseNumber3 {
            get {
                return ResourceManager.GetString("PhaseNumber3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum deviation of the transformation ratio of the main branch, %.
        /// </summary>
        public static string RatioDeviationMainMaximum {
            get {
                return ResourceManager.GetString("RatioDeviationMainMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The minimum deviation of the transformation ratio of the main branch, %.
        /// </summary>
        public static string RatioDeviationMainMinimum {
            get {
                return ResourceManager.GetString("RatioDeviationMainMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum deviation of the transformation ratio of the minor branch, %.
        /// </summary>
        public static string RatioDeviationMinorMaximum {
            get {
                return ResourceManager.GetString("RatioDeviationMinorMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The minimum deviation of the transformation ratio of the minor branch, %.
        /// </summary>
        public static string RatioDeviationMinorMinimum {
            get {
                return ResourceManager.GetString("RatioDeviationMinorMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum deviation of short-circuit voltage of the main branch, %.
        /// </summary>
        public static string ShortCircuitVoltageDeviationMaximum {
            get {
                return ResourceManager.GetString("ShortCircuitVoltageDeviationMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimum deviation of short-circuit voltage of the main branch, %.
        /// </summary>
        public static string ShortCircuitVoltageDeviationMinimum {
            get {
                return ResourceManager.GetString("ShortCircuitVoltageDeviationMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Short circuit voltage, %.
        /// </summary>
        public static string ShortCircuitVoltageNominal {
            get {
                return ResourceManager.GetString("ShortCircuitVoltageNominal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of steps.
        /// </summary>
        public static string StepNumber {
            get {
                return ResourceManager.GetString("StepNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4.
        /// </summary>
        public static string StepNumber4 {
            get {
                return ResourceManager.GetString("StepNumber4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 8.
        /// </summary>
        public static string StepNumber8 {
            get {
                return ResourceManager.GetString("StepNumber8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Step voltage, %.
        /// </summary>
        public static string StepVoltage {
            get {
                return ResourceManager.GetString("StepVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.5.
        /// </summary>
        public static string StepVoltage25 {
            get {
                return ResourceManager.GetString("StepVoltage25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Temperature rise of structural elements, С.
        /// </summary>
        public static string StructuralElementsExcessTemperature {
            get {
                return ResourceManager.GetString("StructuralElementsExcessTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Excess temperature of the magnetic system, С.
        /// </summary>
        public static string SystemMagneticExcessTemperature {
            get {
                return ResourceManager.GetString("SystemMagneticExcessTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Test voltage of internal insulation IKPN high voltage, V.
        /// </summary>
        public static string TestIKPNHighVoltage {
            get {
                return ResourceManager.GetString("TestIKPNHighVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Test voltage of internal insulation IKPN low voltage, V.
        /// </summary>
        public static string TestIKPNLowVoltage {
            get {
                return ResourceManager.GetString("TestIKPNLowVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Test voltage of external insulation of PGI high voltage, V.
        /// </summary>
        public static string TestLI1ExHighVoltage {
            get {
                return ResourceManager.GetString("TestLI1ExHighVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Test voltage of external insulation of PGI low voltage, V.
        /// </summary>
        public static string TestLI1ExLowVoltage {
            get {
                return ResourceManager.GetString("TestLI1ExLowVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Test voltage of internal insulation of PGI high voltage, V.
        /// </summary>
        public static string TestLI1HighVoltage {
            get {
                return ResourceManager.GetString("TestLI1HighVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Test voltage of internal insulation of PGI low voltage, V.
        /// </summary>
        public static string TestLI1LowVoltage {
            get {
                return ResourceManager.GetString("TestLI1LowVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Test voltage of internal insulation GIMV high voltage, V.
        /// </summary>
        public static string TestLI3HighVoltage {
            get {
                return ResourceManager.GetString("TestLI3HighVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Test voltage of internal insulation GIMV low voltage, V.
        /// </summary>
        public static string TestLI3LowVoltage {
            get {
                return ResourceManager.GetString("TestLI3LowVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Test voltage of external insulation PKPN high voltage, V.
        /// </summary>
        public static string TestPKPNExHighVoltage {
            get {
                return ResourceManager.GetString("TestPKPNExHighVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Test voltage of external insulation PKPN low voltage, V.
        /// </summary>
        public static string TestPKPNExLowVoltage {
            get {
                return ResourceManager.GetString("TestPKPNExLowVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Internal insulation test voltage PKPN high voltage, V.
        /// </summary>
        public static string TestPKPNHighVoltage {
            get {
                return ResourceManager.GetString("TestPKPNHighVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Internal insulation test voltage PKPN low voltage, V.
        /// </summary>
        public static string TestPKPNLowVoltage {
            get {
                return ResourceManager.GetString("TestPKPNLowVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Internal insulation test voltage SGI high voltage, V.
        /// </summary>
        public static string TestSI1HighVoltage {
            get {
                return ResourceManager.GetString("TestSI1HighVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Internal insulation test voltage SGI low voltage, V.
        /// </summary>
        public static string TestSI1LowVoltage {
            get {
                return ResourceManager.GetString("TestSI1LowVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum deviation of total losses, %.
        /// </summary>
        public static string TotalLossesDeviationMaximum {
            get {
                return ResourceManager.GetString("TotalLossesDeviationMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimum deviation of total losses, %.
        /// </summary>
        public static string TotalLossesDeviationMinimum {
            get {
                return ResourceManager.GetString("TotalLossesDeviationMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total losses, W.
        /// </summary>
        public static string TotalLossesNominal {
            get {
                return ResourceManager.GetString("TotalLossesNominal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apparent power, kVA.
        /// </summary>
        public static string TransformerPower {
            get {
                return ResourceManager.GetString("TransformerPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Upper working value of air temperature, С.
        /// </summary>
        public static string UpperOperatingTemperature {
            get {
                return ResourceManager.GetString("UpperOperatingTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1000.
        /// </summary>
        public static string VoltageClass1000 {
            get {
                return ResourceManager.GetString("VoltageClass1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 10000.
        /// </summary>
        public static string VoltageClass10000 {
            get {
                return ResourceManager.GetString("VoltageClass10000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 15000.
        /// </summary>
        public static string VoltageClass15000 {
            get {
                return ResourceManager.GetString("VoltageClass15000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 20000.
        /// </summary>
        public static string VoltageClass20000 {
            get {
                return ResourceManager.GetString("VoltageClass20000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 24000.
        /// </summary>
        public static string VoltageClass24000 {
            get {
                return ResourceManager.GetString("VoltageClass24000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 27000.
        /// </summary>
        public static string VoltageClass27000 {
            get {
                return ResourceManager.GetString("VoltageClass27000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3000.
        /// </summary>
        public static string VoltageClass3000 {
            get {
                return ResourceManager.GetString("VoltageClass3000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 35000.
        /// </summary>
        public static string VoltageClass35000 {
            get {
                return ResourceManager.GetString("VoltageClass35000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 6000.
        /// </summary>
        public static string VoltageClass6000 {
            get {
                return ResourceManager.GetString("VoltageClass6000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Voltage class high voltage, V.
        /// </summary>
        public static string VoltageClassHighVoltage {
            get {
                return ResourceManager.GetString("VoltageClassHighVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Voltage class low voltage, V.
        /// </summary>
        public static string VoltageClassLowVoltage {
            get {
                return ResourceManager.GetString("VoltageClassLowVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Voltage linear nominal high voltage, V.
        /// </summary>
        public static string VoltageLinearNominalHighVoltage {
            get {
                return ResourceManager.GetString("VoltageLinearNominalHighVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Voltage linear nominal low voltage, V.
        /// </summary>
        public static string VoltageLinearNominalLowVoltage {
            get {
                return ResourceManager.GetString("VoltageLinearNominalLowVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Excess of the average temperature of the high voltage winding, С.
        /// </summary>
        public static string WindingHighVoltageExcessTemperature {
            get {
                return ResourceManager.GetString("WindingHighVoltageExcessTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Excess of the average temperature of the low voltage winding, С.
        /// </summary>
        public static string WindingLowVoltageExcessTemperature {
            get {
                return ResourceManager.GetString("WindingLowVoltageExcessTemperature", resourceCulture);
            }
        }
    }
}
